name: Quickstarts

on:
  push:
    branches:
      - v0.11
    paths:
      - 'quickstarts/**'
      - '.github/workflows/quickstarts.yaml'
  pull_request:
    types: [opened, synchronize, reopened, closed]
    branches:
      - v0.11
    paths:
      - 'quickstarts/**'
      - '.github/workflows/quickstarts.yaml'

env:
  VERSION: ${{ github.event.pull_request.number || '0.11' }}
  # Use radiusdev.azurecr.io for PR build. Otherwise, use radius.azurecr.io.
  DOCKER_REGISTRY: ${{ github.event.pull_request.number && 'radiusdev.azurecr.io' || 'radius.azurecr.io' }}

jobs:
  build:
    name: Build and push quickstart container images
    if: github.event.action != 'closed'
    runs-on: ubuntu-latest
  steps:
    - name: Checkout code
      uses: actions/checkout@v2

      
    