name: Test Quickstarts

on:
  workflow_dispatch:
    inputs:
      initFlags:
        description: 'Optional flags to specify when initializing the Radius dev environment'
        required: false
        default: ''

jobs:
  build:
    name: Deploy quickstarts to local environment
    if: github.event.action != 'closed'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Download k3d
        run: wget -q -O - https://raw.githubusercontent.com/k3d-io/k3d/main/install.sh | bash
      - name: Download rad
        run: wget -q "https://get.radapp.dev/tools/rad/install.sh" -O - | /bin/bash
      - name: Init local environment
        run: rad env init dev ${{ github.event.inputs.initFlags }}
      - name: Deploy webapp
        run: |
          rad deploy ./quickstarts/webapp/template.bicep
          rad app delete webapp -y
      - name: Deploy Dapr
        run: |
          rad deploy ./quickstarts/dapr/dapr.bicep
          rad app delete dapr-tutorial -y
